version: '3.5'
services:
    comfino-prestashop-php:
        build:
            context: ./
            dockerfile: docker/Dockerfile
        working_dir: /comfino-woocommerce
        tty: true
        volumes:
            - ./:/comfino-woocommerce
            - ~/.composer:/home/vagrant/.composer
